package cli

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/urfave/cli/v3"

	"github.com/esops-dev/esops-doctor/internal/exit"
	"github.com/esops-dev/esops-doctor/internal/findings"
	"github.com/esops-dev/esops-doctor/internal/rules"
)

// newProfileCommand prints a profile-shaped YAML skeleton on stdout
// listing every catalog rule as a commented-out severity_overrides
// entry. The operator pipes the output to a file, edits it, and feeds
// the result back via `scan --profile-file PATH`.
//
// Honours --rules-dir so a custom catalog (with overrides) shows up in
// the generated severity_overrides list — otherwise an operator who
// ships their own rules would have no idea those IDs are tunable from
// a profile.
func newProfileCommand() *cli.Command {
	return &cli.Command{
		Name:  "new-profile",
		Usage: "Print a profile YAML skeleton on stdout",
		Description: "Emits a fully-formed profile YAML on stdout, listing every rule\n" +
			"in the catalog as a commented-out severity_overrides entry with\n" +
			"its current default severity. Pipe to a file, uncomment the rules\n" +
			"you want to tune, and feed the file back with `scan --profile-file`.\n\n" +
			"Custom catalogs are honoured: --rules-dir is layered before the\n" +
			"skeleton is rendered so a profile authored against a project's own\n" +
			"rule set sees those IDs in the output.",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "name",
				Value: "custom",
				Usage: "Value for the generated profile's `name:` field",
			},
			&cli.StringFlag{
				Name:  "rules-dir",
				Usage: "Additional directory of rule YAML files layered over the embedded catalog before listing",
			},
		},
		Action: func(_ context.Context, cmd *cli.Command) error {
			return runNewProfile(cmd, cmdWriter(cmd))
		},
	}
}

func runNewProfile(cmd *cli.Command, stdout io.Writer) error {
	cat, err := loadLayeredCatalog(cmd.String("rules-dir"))
	if err != nil {
		return err
	}
	name := strings.TrimSpace(cmd.String("name"))
	if name == "" {
		return exit.Usage("--name must not be empty")
	}
	return renderProfileSkeleton(stdout, name, cat)
}

// renderProfileSkeleton writes a YAML profile to w listing every rule
// in cat as a commented-out severity_overrides entry. The output is
// stable: rules are listed alphabetically by ID and severities mirror
// the rule's declared default.
func renderProfileSkeleton(w io.Writer, name string, cat *rules.Catalog) error {
	if _, err := fmt.Fprintf(w, header, name); err != nil {
		return fmt.Errorf("writing profile skeleton: %w", err)
	}
	ids := make([]string, 0, len(cat.Rules))
	severities := make(map[string]findings.Severity, len(cat.Rules))
	for _, r := range cat.Rules {
		ids = append(ids, r.ID)
		severities[r.ID] = r.Severity
	}
	sort.Strings(ids)
	for _, id := range ids {
		// Each row is commented out so the generated profile is a
		// no-op until the operator opts a rule in. The severity shown
		// is the rule's current default so an operator can see what
		// they would override.
		sev := severities[id].String()
		if sev == "" || sev == "unknown" {
			sev = "warn"
		}
		if _, err := fmt.Fprintf(w, "  # %s: %s\n", id, sev); err != nil {
			return fmt.Errorf("writing profile skeleton: %w", err)
		}
	}
	if _, err := io.WriteString(w, footer); err != nil {
		return fmt.Errorf("writing profile skeleton: %w", err)
	}
	return nil
}

// header is the part of the skeleton that does not depend on the rule
// catalog. Carries the operator-facing comments that explain each
// section, so the generated file is self-documenting on its own.
const header = `# Profile generated by esops-doctor new-profile.
#
# Save to a file in this repository (e.g. ./%[1]s.yaml) and pass it
# to a scan with:
#
#   esops-doctor scan --profile-file ./%[1]s.yaml
#
# The path is yours to pick — there is no auto-discovery directory;
# --profile-file always names the file explicitly.
#
# Profiles override the default severity of named rules and narrow the
# scan to a tag- or id-selected subset. Every block below is optional:
# leave it empty to keep the catalog's defaults.

name: %[1]s
description: ""

# severity_overrides rewrites a rule's default severity. Useful when
# an environment treats a warn-level finding as critical (or vice
# versa). Uncomment the rules you want to tune and adjust the level;
# the listed value is the rule's current default.
severity_overrides:
`

const footer = `
# include_tags narrows the scan to rules carrying any of these tags.
# Empty = no constraint (every rule runs).
include_tags: []

# skip_tags drops rules carrying any of these tags. skip_tags wins over
# include_tags so it can subtract from a tag-narrowed selection.
skip_tags: []

# rule_ids narrows the scan to these specific IDs. Empty = no
# constraint.
rule_ids: []
`
